#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx


- name: Install Nginx
  apt:
    name: nginx
    state: latest
  become: true 
  notify: Restart Nginx

- name: Configure Nginx site for Symfony project
  become: true
  template:
    src: templates/symfony.conf
    dest: /etc/nginx/sites-available/{{ server_name }}.conf
  notify: Restart Nginx

- name: Enable Nginx site
  become: true
  file:
    src: /etc/nginx/sites-available/{{ server_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ server_name }}.conf
    state: link
  notify: Restart Nginx
    
- name: Add eanabled Nginx  site /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ server_name }}"
    regexp: '127\.0\.0\.1\s+{{ server_name }}'
    state: present
  become: true